Resources:
  AutoScalingLaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      IamInstanceProfile: "arn:aws:iam::175722996601:instance-profile/SQS-S3-Role" 
      ImageId: String #required
      InstanceType: String #required
      LaunchConfigurationName: "Ares Launch Config"
      PlacementTenancy: default
      SecurityGroups:
      - String
      SpotPrice: String
      UserData: String
  !LogicalID:
    Type: "AWS::EC2::SpotFleet"
    Properties:
      SpotFleetRequestConfigData: #required
        SpotFleetRequestConfigData
  