AWSTemplateFormatVersion: '2010-09-09'
Resources:
	S3Bucket:
		Type: AWS::S3::Bucket
		Properties: 
			DeletionPolicy: Retain
			AccessControl: Private
			NotificationConfiguration:
				TopicConfigurations:
					- Topic: !Ref SNSTopic
						Event: s3:ObjectCreated:*
	SQSqueue:
		Type: AWS::SQS::Queue
	SNSTopic:
		Type: AWS::SNS

Outputs:
	BucketName:
		Value: !Ref 'S3Bucket'
		Description: Name of bucket created
